blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://www.nvidia.com/object/submit-security-vulnerability.html
    about: Report security vulnerabilities privately to NVIDIA PSIRT.
