# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.registryCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.registryCredentials.name }}
  labels:
    {{- include "mosaic-stack.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict .Values.global.registryCredentials.server (dict "username" .Values.global.registryCredentials.username "password" .Values.global.registryCredentials.password "email" .Values.global.registryCredentials.email "auth" (printf "%s:%s" .Values.global.registryCredentials.username .Values.global.registryCredentials.password | b64enc))) | toJson | quote }}
{{- end }}
